#!/bin/bash

SOIL_PATH=$(pwd)
. $SOIL_PATH/basics/config
. $SOIL_PATH/basics/functions

echo $SOIL_PATH
echo $config

# Calling the git script
callScript git.sh

# Calling the ssh script
callScript ssh.sh

# Calling the bash script
callScript bash.sh
