#!/bin/bash

SCRIPT_PATH=scripts/

function callScript(){
	local script=$SCRIPT_PATH$1
	read -p "Shall the script $1 be executed? (Y/n)" yn
	case $yn in
		[Yy]* ) echo "$1 gets executed."; . $script;;
		[Nn]* ) echo "$1 will NOT be executed.";;
		* ) echo "$1 gets executed."; . $script;;
	esac
}
